package com.hc360.mobileaccount.dao;

import java.util.List;
import java.util.Map;

import com.hc360.mobileaccount.po.Audio;
import com.hc360.mobileaccount.po.Course;
import com.hc360.mobileaccount.po.CourseChapter;
import com.hc360.mobileaccount.po.Fans;
import com.hc360.mobileaccount.po.PhotoAlbum;
import com.hc360.mobileaccount.po.Picture;
import com.hc360.mobileaccount.po.Teacher;
import com.hc360.mobileaccount.po.TeacherReplyInvited;
import com.hc360.mobileaccount.po.UserComment;
import com.hc360.mobileaccount.po.UserNreply;
import com.hc360.mobileaccount.po.UserPraise;
import com.hc360.mobileaccount.po.UserQuestion;
import com.hc360.mobileaccount.po.UserSubscribeTeacher;
import com.hc360.mobileaccount.po.UserTalk;
import com.hc360.mobileaccount.po.Video;

public interface SaleTeacherMapper {
	public Teacher getById(Long id);
	public Teacher getByUserId(Long userId);
	public List<Long> getTeacherIdsByLabelId(Long labelId);
	public List<Long> getAllTeacherIds();
	public void batchInsertTeacherReplyInvited(List<TeacherReplyInvited> inviteList);
	public void insertIntoUserSubscribeTeacher(UserSubscribeTeacher t);
	public void unsubscribeTeacher(UserSubscribeTeacher t);
	public List<Long> getTeacherCourseIds(Long userid);
	public int isSubscribeTeacher(UserSubscribeTeacher t);
	public List<Long> getSubUserIds(Long teacherid);
	public void insertTeacher(Teacher t);
	public void updateTeacher(Teacher t);
	public int getInvitedRepliesCount(Map<String,Object> map);
	public List<TeacherReplyInvited> getTeacherReplyInvitedList(TeacherReplyInvited in);
	public List<TeacherReplyInvited> getInvitedTeacherList(TeacherReplyInvited in);
	
	int getCommentCount(long userID);
	int getFansCount(long userID);
	String getFansStartDate(Map<String,Object> map);
	List<Course> getCourseList(long userID);
	Course getCourseById(long courseID);
	int editCourse(Course course);
	int editCourseGrade(Course course);
	int delCourse(int courseID);
	int delCourseChapter(int courseID);
	int editCourseChapter(CourseChapter courseChapter);
	int addAudio(Audio audio);
	int addResourse(Map<String,Object> map);
	int delAudio(long id);
	int delChapter(long chapterID);
	int delChapterVideo(long chapterID);
	int delChapterAudio(long chapterID);
	int delChapterPicture(long chapterID);
	int delResourse(long chapterid);
	int addCourse(Course course);
	int addTeacherCourse(Map<String,Object> map);
	int addCourseGrade(Map<String,Object> map);
	int addCourseChapter(CourseChapter courseChapter);
	List<PhotoAlbum> getAlbums(Map<String,Object> map);
	String getAlbumsStartDate(Map<String,Object> map);
	int getAlbumsCount(Long userID);
	int delAlbums(long id);
	List<Fans> getFans(Map<String,Object> map);
	List<UserQuestion> getInvitedQuestions(Map<String,Object> map);
	int getInvitedQuestionsCount(long userID);
	int editReplyInvitedState(Map<String,Object> map);
	List<UserQuestion> getUserQuestions(Map<String,Object> map);
	int getUserQuestionsCount(Map<String,Object> map);
	List<UserTalk> getRepliedTalks(Map<String,Object> map);
	int  getRepliedTalksCount(long userID);
	public List<UserNreply> getObjectSimpleReplys(Map<String,Object> map);
	public List<UserNreply> getObjectReplys(Map<String,Object> map);
	public List<UserNreply> getObjectOrderReplys(Map<String,Object> map);
	public List<UserNreply> getObjectSonReplys(Map<String,Object> map);
	
	List<UserPraise> getUserPraises(Map<String,Object> map);
	List<UserTalk> getUserTalks(Map<String,Object> map);
	int getUserTalksCount(Map<String,Object> map);
	int addAlbums(PhotoAlbum photoAlbum);
	int addVideo(Video video);
	int addPicture(Picture picture);
	CourseChapter getCourseChapter(long chapterID);
	Video getChapterVideo(long chapterID);
	List<Audio> getChapterAudio(long chapterID);
	List<Picture> getChapterPicture(long chapterID);
	List<UserComment> getCourseComments(Map<String,Object> map);
	int getCourseCommentsCount(long userID);
}